from sqlalchemy import Column, String, Text, Boolean, Integer, ForeignKey, JSON
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.core.database import Base
from app.models.base import BaseModelMixin


class TenderClause(Base, BaseModelMixin):
    __tablename__ = "tender_clauses"

    tender_id = Column(UUID(as_uuid=True), ForeignKey("tenders.id", ondelete="CASCADE"), nullable=False, index=True)
    clause_code = Column(String(50), nullable=False, index=True)  # e.g., TECH-01, FIN-01, STAT-01
    category = Column(String(100), default="TECHNICAL", nullable=False)  # TECHNICAL, FINANCIAL, STATUTORY, EXPERIENCE, DELIVERY_SLA
    title = Column(String(300), nullable=False)
    description = Column(Text, nullable=False)
    is_mandatory = Column(Boolean, default=True, nullable=False)

    # Draft rule generated by LLM until confirmed by human officer
    rule_config = Column(JSON, nullable=True)

    # Provenance fields: exact text quote & source page in the tender PDF
    source_text = Column(Text, nullable=False)
    page_number = Column(Integer, nullable=False)

    # Human-in-the-loop confirmation state
    is_confirmed = Column(Boolean, default=False, nullable=False)

    # Relationships
    tender = relationship("Tender", back_populates="clauses")
    evaluations = relationship("ComplianceEvaluation", back_populates="clause", cascade="all, delete-orphan")
